seems to work :shipit:
crystal-linux/jade-tui pull request #2
Opened 2022-08-29 02:43 UTC by SomethingGeneric

@not-my-segfault sanity check?

2022-08-29 13:59 UTC, not-my-segfault requested changes

2022-08-29 13:59 UTC, mchalunderscore commented on PKGBUILD
> +    mkdir -p ${pkgdir}/usr/{share/jade-tui,bin}
we should ideally be using the `install` command to do this and `cp` and set perms all at once, I believe my new `pkg-warner` tool has an example of this in its PKGBUILD

2022-08-29 20:44 UTC, SomethingGeneric commented
@not-my-segfault does this syntax for `install` look correct?

2022-08-29 21:05 UTC, not-my-segfault commented
`-D -m` can be shortened to `-Dm` but otherwise this is perfect 👍

2022-08-29 22:26 UTC, not-my-segfault approved these changes

2022-08-29 22:51 UTC, not-my-segfault commented
@axtloss Could you check this over so we can merge please? Thank you

2022-08-30 04:05 UTC, axtloss commented
LGTM, @ShyyLexi would you say the current jade-tui can be merged into main?

2022-08-30 10:36 UTC, ShyyLexi commented
Yea it's mostly still the same, just manual partition is not working yet

2022-08-30 11:44 UTC, axtloss approved these changes

2022-08-30 11:45 UTC, merged